name: Chart Repo PR Action
author: Austin Dewey <deweya964@gmail.com>
description: Automatically make a PR to an upstream chart repository
branding:
  icon: 'git-pull-request'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  token:
    description: Token used to push to fork
    required: true